import { DomainSupervisor } from '../../types/index.js';
import { ALL_100_AGENTS } from '../agents/registry.js';

export const DOMAIN_SUPERVISORS: DomainSupervisor[] = [
  {
    id: 'sup.executive',
    name: 'Executive & C-Suite Supervisor',
    domain: 'Executive',
    level: 2,
    description: 'Decomposes corporate goals across C-Suite officers (CEO, COO, CFO, CTO, CPO, CMO, CRO, CHRO, Risk, Strategy).',
    specialistIds: ALL_100_AGENTS.filter((a) => a.supervisorId === 'sup.executive').map((a) => a.id),
  },
  {
    id: 'sup.orchestration',
    name: 'Orchestration & Workflow Supervisor',
    domain: 'Orchestration',
    level: 2,
    description: 'Supervises workflow dispatch, DAG topology, dependency analysis, runtime monitoring, and recovery.',
    specialistIds: ALL_100_AGENTS.filter((a) => a.supervisorId === 'sup.orchestration').map((a) => a.id),
  },
  {
    id: 'sup.memory',
    name: 'Organizational Memory & Knowledge Supervisor',
    domain: 'Memory',
    level: 2,
    description: 'Oversees memory federation, episodic and semantic storage, knowledge graphs, and memory validation.',
    specialistIds: ALL_100_AGENTS.filter((a) => a.supervisorId === 'sup.memory').map((a) => a.id),
  },
  {
    id: 'sup.strategy',
    name: 'Strategy & Competitive Intelligence Supervisor',
    domain: 'Strategy',
    level: 2,
    description: 'Decomposes strategic mandates, market research, competitor deep-dives, scenario planning, and strategic synthesis.',
    specialistIds: ALL_100_AGENTS.filter((a) => a.supervisorId === 'sup.strategy').map((a) => a.id),
  },
  {
    id: 'sup.finance',
    name: 'Finance & Capital Allocation Supervisor',
    domain: 'Finance',
    level: 2,
    description: 'Coordinates financial analysis, unit economics, budget allocations, cash flow monitoring, and M&A evaluations.',
    specialistIds: ALL_100_AGENTS.filter((a) => a.supervisorId === 'sup.finance').map((a) => a.id),
  },
  {
    id: 'sup.sales',
    name: 'Commercial & Sales Pipeline Supervisor',
    domain: 'Sales',
    level: 2,
    description: 'Supervises enterprise sales strategy, prospect research, predictive qualification, and pipeline progression.',
    specialistIds: ALL_100_AGENTS.filter((a) => a.supervisorId === 'sup.sales').map((a) => a.id),
  },
  {
    id: 'sup.marketing',
    name: 'Marketing & Brand Strategy Supervisor',
    domain: 'Marketing',
    level: 2,
    description: 'Orchestrates campaigns, editorial content, CAC optimization, brand positioning, and product-led growth loops.',
    specialistIds: ALL_100_AGENTS.filter((a) => a.supervisorId === 'sup.marketing').map((a) => a.id),
  },
  {
    id: 'sup.product',
    name: 'Product Management & UX Supervisor',
    domain: 'Product',
    level: 2,
    description: 'Supervises PRD specifications, customer research, feature roadmaps, UX wireframes, and value propositions.',
    specialistIds: ALL_100_AGENTS.filter((a) => a.supervisorId === 'sup.product').map((a) => a.id),
  },
  {
    id: 'sup.engineering',
    name: 'Engineering & Technical Architecture Supervisor',
    domain: 'Engineering',
    level: 2,
    description: 'Directs systems architecture, software implementation, QA automation, DevOps deployments, and tech debt reduction.',
    specialistIds: ALL_100_AGENTS.filter((a) => a.supervisorId === 'sup.engineering').map((a) => a.id),
  },
  {
    id: 'sup.operations',
    name: 'Operations & Supply Chain Supervisor',
    domain: 'Operations',
    level: 2,
    description: 'Manages core business processes, procurement negotiations, supplier risk, inventory, and business continuity.',
    specialistIds: ALL_100_AGENTS.filter((a) => a.supervisorId === 'sup.operations').map((a) => a.id),
  },
  {
    id: 'sup.hr',
    name: 'People, Talent & HR Supervisor',
    domain: 'People & HR',
    level: 2,
    description: 'Oversees talent acquisition, candidate screening, employee onboarding, performance calibrations, and culture.',
    specialistIds: ALL_100_AGENTS.filter((a) => a.supervisorId === 'sup.hr').map((a) => a.id),
  },
  {
    id: 'sup.legal',
    name: 'Legal Counsel & Contracts Supervisor',
    domain: 'Legal',
    level: 2,
    description: 'Coordinates corporate legal research, liability clause redlining, contract drafting, and intellectual property.',
    specialistIds: ALL_100_AGENTS.filter((a) => a.supervisorId === 'sup.legal').map((a) => a.id),
  },
  {
    id: 'sup.security',
    name: 'Cybersecurity & Data Privacy Supervisor',
    domain: 'Security',
    level: 2,
    description: 'Supervises threat intelligence, vulnerability remediation, GDPR/CCPA privacy controls, and access boundaries.',
    specialistIds: ALL_100_AGENTS.filter((a) => a.supervisorId === 'sup.security').map((a) => a.id),
  },
  {
    id: 'sup.governance',
    name: 'Governance, Ethics & Audit Supervisor',
    domain: 'Governance',
    level: 2,
    description: 'Enforces AI alignment, company policies, SOC 2 compliance, and immutable forensic audit logging.',
    specialistIds: ALL_100_AGENTS.filter((a) => a.supervisorId === 'sup.governance').map((a) => a.id),
  },
  {
    id: 'sup.customer',
    name: 'Customer Success & Intelligence Supervisor',
    domain: 'Customer',
    level: 2,
    description: 'Supervises customer support triage, account health scoring, NPS feedback clustering, and churn retention.',
    specialistIds: ALL_100_AGENTS.filter((a) => a.supervisorId === 'sup.customer').map((a) => a.id),
  },
];

export const SUPERVISOR_BY_ID = new Map<string, DomainSupervisor>(
  DOMAIN_SUPERVISORS.map((s) => [s.id, s])
);
