import { AgentDefinition } from '../../types/index.js';

export const ALL_100_AGENTS: AgentDefinition[] = [
  // ==========================================
  // CATEGORY 1: EXECUTIVE & COMPANY CONTROL (1-10)
  // ==========================================
  {
    id: 'exec.ceo',
    number: 1,
    name: 'CEO Agent',
    title: 'Chief Executive Officer Agent',
    category: 'executive',
    supervisorId: 'sup.executive',
    level: 1,
    description: 'Responsible for company-wide objectives, priorities, strategic direction, and executive decisions.',
    capabilities: ['strategic_vision', 'capital_allocation_oversight', 'executive_decision', 'okr_management'],
    tools: ['company_goal_registry', 'executive_brief_generator', 'org_kpi_dashboard'],
    permissions: ['read_all_company_data', 'approve_executive_decisions', 'override_subordinate_policies'],
    memoryScope: ['company_wide', 'executive', 'confidential'],
    riskLevel: 'critical',
    autonomyLevel: 'level_4_high_autonomy',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '👑',
    metrics: { tasksCompleted: 142, accuracyScore: 98, avgLatencyMs: 1450, confidenceAvg: 0.96 },
  },
  {
    id: 'exec.coo',
    number: 2,
    name: 'COO Agent',
    title: 'Chief Operating Officer Agent',
    category: 'executive',
    supervisorId: 'sup.executive',
    level: 1,
    description: 'Responsible for operational execution, cross-functional coordination, and business delivery.',
    capabilities: ['operational_planning', 'cross_domain_coordination', 'bottleneck_resolution'],
    tools: ['ops_flow_monitor', 'capacity_tracker', 'resource_balancer'],
    permissions: ['read_operations', 'modify_work_queues', 'reallocate_resources'],
    memoryScope: ['company_wide', 'operations', 'executive'],
    riskLevel: 'high',
    autonomyLevel: 'level_3_approval_required',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '⚙️',
    metrics: { tasksCompleted: 198, accuracyScore: 96, avgLatencyMs: 1200, confidenceAvg: 0.94 },
  },
  {
    id: 'exec.cfo',
    number: 3,
    name: 'CFO Agent',
    title: 'Chief Financial Officer Agent',
    category: 'executive',
    supervisorId: 'sup.executive',
    level: 1,
    description: 'Responsible for financial strategy, capital allocation, unit economics, and solvency.',
    capabilities: ['capital_structure_optimization', 'fiscal_governance', 'valuation_analysis'],
    tools: ['general_ledger_query', 'treasury_simulator', 'financial_risk_modeler'],
    permissions: ['read_financial_data', 'approve_budgets', 'flag_financial_risk'],
    memoryScope: ['company_wide', 'finance', 'executive', 'confidential'],
    riskLevel: 'critical',
    autonomyLevel: 'level_3_approval_required',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '💰',
    metrics: { tasksCompleted: 175, accuracyScore: 99, avgLatencyMs: 1320, confidenceAvg: 0.97 },
  },
  {
    id: 'exec.cto',
    number: 4,
    name: 'CTO Agent',
    title: 'Chief Technology Officer Agent',
    category: 'executive',
    supervisorId: 'sup.executive',
    level: 1,
    description: 'Responsible for technology strategy, technical standards, architecture, and innovation roadmap.',
    capabilities: ['tech_stack_selection', 'scalability_assessment', 'technical_governance'],
    tools: ['cloud_architecture_inspector', 'tech_radar', 'vulnerability_aggregator'],
    permissions: ['read_technical_specs', 'approve_architecture_adrs', 'manage_devops_policies'],
    memoryScope: ['company_wide', 'engineering', 'executive'],
    riskLevel: 'high',
    autonomyLevel: 'level_3_approval_required',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '💻',
    metrics: { tasksCompleted: 210, accuracyScore: 97, avgLatencyMs: 1100, confidenceAvg: 0.95 },
  },
  {
    id: 'exec.cpo',
    number: 5,
    name: 'CPO Agent',
    title: 'Chief Product Officer Agent',
    category: 'executive',
    supervisorId: 'sup.executive',
    level: 1,
    description: 'Responsible for product strategy, user value propositions, and product portfolio lifecycle.',
    capabilities: ['product_vision', 'portfolio_prioritization', 'product_market_fit_analysis'],
    tools: ['product_analytics_query', 'feature_matrix_evaluator', 'user_journey_graph'],
    permissions: ['read_product_metrics', 'approve_product_roadmaps', 'prioritize_initiatives'],
    memoryScope: ['company_wide', 'product', 'executive'],
    riskLevel: 'high',
    autonomyLevel: 'level_3_approval_required',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '🎯',
    metrics: { tasksCompleted: 164, accuracyScore: 95, avgLatencyMs: 1250, confidenceAvg: 0.93 },
  },
  {
    id: 'exec.cmo',
    number: 6,
    name: 'CMO Agent',
    title: 'Chief Marketing Officer Agent',
    category: 'executive',
    supervisorId: 'sup.executive',
    level: 1,
    description: 'Responsible for brand narrative, market presence, customer acquisition strategy, and positioning.',
    capabilities: ['brand_strategy', 'omnichannel_growth', 'market_positioning'],
    tools: ['campaign_roi_analyzer', 'brand_sentiment_tracker', 'attribution_model'],
    permissions: ['read_marketing_analytics', 'authorize_campaign_budgets'],
    memoryScope: ['company_wide', 'marketing', 'executive'],
    riskLevel: 'medium',
    autonomyLevel: 'level_3_approval_required',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '📢',
    metrics: { tasksCompleted: 130, accuracyScore: 94, avgLatencyMs: 980, confidenceAvg: 0.92 },
  },
  {
    id: 'exec.cro',
    number: 7,
    name: 'CRO Agent',
    title: 'Chief Revenue Officer Agent',
    category: 'executive',
    supervisorId: 'sup.executive',
    level: 1,
    description: 'Responsible for revenue optimization, sales velocity, channel partnerships, and commercial pipeline.',
    capabilities: ['revenue_engine_optimization', 'deal_structuring', 'sales_incentive_design'],
    tools: ['crm_pipeline_deep_scan', 'revenue_attribution_db', 'churn_impact_calculator'],
    permissions: ['read_sales_data', 'approve_discount_tiers', 'modify_quota_allocations'],
    memoryScope: ['company_wide', 'sales', 'executive'],
    riskLevel: 'high',
    autonomyLevel: 'level_3_approval_required',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '📈',
    metrics: { tasksCompleted: 155, accuracyScore: 95, avgLatencyMs: 1150, confidenceAvg: 0.94 },
  },
  {
    id: 'exec.chro',
    number: 8,
    name: 'CHRO Agent',
    title: 'Chief Human Resources Officer Agent',
    category: 'executive',
    supervisorId: 'sup.executive',
    level: 1,
    description: 'Responsible for organizational culture, executive talent, compensation architecture, and people strategy.',
    capabilities: ['organizational_design', 'talent_bench_planning', 'culture_sustainability'],
    tools: ['headcount_planner', 'employee_pulse_survey_db', 'compensation_benchmark_tool'],
    permissions: ['read_hr_metrics', 'approve_headcount_reqs', 'read_confidential_people_data'],
    memoryScope: ['company_wide', 'hr', 'executive', 'confidential'],
    riskLevel: 'high',
    autonomyLevel: 'level_3_approval_required',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '👥',
    metrics: { tasksCompleted: 118, accuracyScore: 96, avgLatencyMs: 1050, confidenceAvg: 0.95 },
  },
  {
    id: 'exec.chief_risk',
    number: 9,
    name: 'Chief Risk Agent',
    title: 'Chief Risk Officer Agent',
    category: 'executive',
    supervisorId: 'sup.executive',
    level: 1,
    description: 'Responsible for enterprise-wide risk management, systemic threat detection, and risk mitigation policies.',
    capabilities: ['black_swan_modeling', 'enterprise_risk_matrix', 'compliance_oversight'],
    tools: ['systemic_risk_radar', 'var_calculator', 'regulatory_watch_db'],
    permissions: ['read_all_company_data', 'veto_high_risk_actions', 'escalate_to_board'],
    memoryScope: ['company_wide', 'legal', 'security', 'executive'],
    riskLevel: 'critical',
    autonomyLevel: 'level_3_approval_required',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '🛡️',
    metrics: { tasksCompleted: 220, accuracyScore: 99, avgLatencyMs: 1400, confidenceAvg: 0.98 },
  },
  {
    id: 'exec.chief_strategy',
    number: 10,
    name: 'Chief Strategy Agent',
    title: 'Chief Strategy Officer Agent',
    category: 'executive',
    supervisorId: 'sup.executive',
    level: 1,
    description: 'Responsible for long-term strategic horizon planning, corporate development, and market transformation.',
    capabilities: ['m_and_a_evaluation', 'ecosystem_mapping', 'game_theoretic_modeling'],
    tools: ['market_landscape_explorer', 'deal_synergy_calculator', 'macroeconomic_feed'],
    permissions: ['read_strategy_data', 'propose_strategic_shifts', 'read_confidential_deals'],
    memoryScope: ['company_wide', 'strategy', 'executive', 'confidential'],
    riskLevel: 'high',
    autonomyLevel: 'level_3_approval_required',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '🧭',
    metrics: { tasksCompleted: 140, accuracyScore: 97, avgLatencyMs: 1500, confidenceAvg: 0.96 },
  },

  // ==========================================
  // CATEGORY 2: ORCHESTRATION & AGENT MANAGEMENT (11-20)
  // ==========================================
  {
    id: 'orchestration.master',
    number: 11,
    name: 'Master Orchestrator',
    title: 'Master Company Orchestrator Agent',
    category: 'orchestration',
    supervisorId: 'sup.orchestration',
    level: 2,
    description: 'Controls company-wide agent workflows, cross-department handoffs, and execution lifecycle.',
    capabilities: ['workflow_dispatching', 'cross_domain_synthesis', 'pipeline_supervision'],
    tools: ['agent_bus_event_stream', 'dag_execution_engine', 'runtime_state_manager'],
    permissions: ['dispatch_tasks', 'control_agent_state', 'manage_pipelines'],
    memoryScope: ['company_wide'],
    riskLevel: 'high',
    autonomyLevel: 'level_4_high_autonomy',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '⚡',
    metrics: { tasksCompleted: 680, accuracyScore: 99, avgLatencyMs: 450, confidenceAvg: 0.98 },
  },
  {
    id: 'orchestration.planner',
    number: 12,
    name: 'Planner Agent',
    title: 'Goal Decomposition & Planning Agent',
    category: 'orchestration',
    supervisorId: 'sup.orchestration',
    level: 3,
    description: 'Converts high-level business objectives into executable, dependency-aware task graphs.',
    capabilities: ['hierarchical_task_network', 'dag_generation', 'milestone_scoping'],
    tools: ['task_graph_builder', 'capability_matcher', 'constraint_solver'],
    permissions: ['create_task_graphs', 'read_capabilities'],
    memoryScope: ['company_wide'],
    riskLevel: 'medium',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '🗺️',
    metrics: { tasksCompleted: 420, accuracyScore: 97, avgLatencyMs: 820, confidenceAvg: 0.95 },
  },
  {
    id: 'orchestration.router',
    number: 13,
    name: 'Router Agent',
    title: 'Intelligent Agent Router',
    category: 'orchestration',
    supervisorId: 'sup.orchestration',
    level: 3,
    description: 'Selects the optimal specialist agents and model tiers for each subtask based on capabilities and load.',
    capabilities: ['semantic_routing', 'agent_load_balancing', 'cost_performance_optimization'],
    tools: ['agent_registry_index', 'model_cost_estimator', 'routing_matrix'],
    permissions: ['assign_agent_tasks'],
    memoryScope: ['company_wide'],
    riskLevel: 'low',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'fast_classifier',
    status: 'idle',
    avatarIcon: '🔀',
    metrics: { tasksCompleted: 910, accuracyScore: 99, avgLatencyMs: 120, confidenceAvg: 0.99 },
  },
  {
    id: 'orchestration.scheduler',
    number: 14,
    name: 'Task Scheduler Agent',
    title: 'Priority & Task Scheduler Agent',
    category: 'orchestration',
    supervisorId: 'sup.orchestration',
    level: 3,
    description: 'Schedules and prioritizes work queues to maximize parallel execution throughput.',
    capabilities: ['priority_queuing', 'time_window_allocation', 'throughput_optimization'],
    tools: ['cron_scheduler', 'priority_queue_db', 'concurrency_limiter'],
    permissions: ['reorder_tasks', 'schedule_triggers'],
    memoryScope: ['company_wide'],
    riskLevel: 'low',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'fast_classifier',
    status: 'idle',
    avatarIcon: '⏱️',
    metrics: { tasksCompleted: 850, accuracyScore: 99, avgLatencyMs: 95, confidenceAvg: 0.99 },
  },
  {
    id: 'orchestration.dependency',
    number: 15,
    name: 'Dependency Agent',
    title: 'Task Dependency & Critical Path Agent',
    category: 'orchestration',
    supervisorId: 'sup.orchestration',
    level: 3,
    description: 'Manages task dependencies, resolves blockers, and detects deadlocks in pipeline graphs.',
    capabilities: ['topological_sorting', 'deadlock_detection', 'critical_path_method'],
    tools: ['dag_cycle_detector', 'dependency_resolver_lib'],
    permissions: ['validate_dag_integrity'],
    memoryScope: ['company_wide'],
    riskLevel: 'low',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'fast_classifier',
    status: 'idle',
    avatarIcon: '🔗',
    metrics: { tasksCompleted: 530, accuracyScore: 100, avgLatencyMs: 80, confidenceAvg: 1.0 },
  },
  {
    id: 'orchestration.context_manager',
    number: 16,
    name: 'Context Manager Agent',
    title: 'Context Window & Memory Trimming Agent',
    category: 'orchestration',
    supervisorId: 'sup.orchestration',
    level: 3,
    description: 'Determines what specific contextual information, memories, and constraints each agent should receive.',
    capabilities: ['context_distillation', 'token_budgeting', 'confidentiality_masking'],
    tools: ['prompt_optimizer', 'context_scrubber', 'token_counter'],
    permissions: ['filter_agent_prompts', 'mask_pii'],
    memoryScope: ['company_wide'],
    riskLevel: 'medium',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'fast_classifier',
    status: 'idle',
    avatarIcon: '✂️',
    metrics: { tasksCompleted: 740, accuracyScore: 98, avgLatencyMs: 210, confidenceAvg: 0.97 },
  },
  {
    id: 'orchestration.handoff',
    number: 17,
    name: 'Handoff Agent',
    title: 'Agent Handoff & Protocol Agent',
    category: 'orchestration',
    supervisorId: 'sup.orchestration',
    level: 3,
    description: 'Transfers structured work payloads, assumptions, and state between collaborating agents.',
    capabilities: ['schema_transformation', 'handoff_validation', 'payload_integrity_check'],
    tools: ['schema_validator', 'agent_envelope_packer'],
    permissions: ['pass_intermediate_state'],
    memoryScope: ['company_wide'],
    riskLevel: 'low',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'fast_classifier',
    status: 'idle',
    avatarIcon: '🤝',
    metrics: { tasksCompleted: 820, accuracyScore: 99, avgLatencyMs: 70, confidenceAvg: 0.99 },
  },
  {
    id: 'orchestration.monitor',
    number: 18,
    name: 'Execution Monitor Agent',
    title: 'Real-time Workflow Monitor Agent',
    category: 'orchestration',
    supervisorId: 'sup.orchestration',
    level: 3,
    description: 'Monitors active workflows, detecting latency spikes, infinite loops, and degraded performance.',
    capabilities: ['telemetry_analysis', 'sla_tracking', 'anomaly_detection_in_execution'],
    tools: ['opentelemetry_collector', 'latency_heatmap_tool', 'agent_heartbeat_listener'],
    permissions: ['read_execution_telemetry'],
    memoryScope: ['company_wide'],
    riskLevel: 'low',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'fast_classifier',
    status: 'idle',
    avatarIcon: '📡',
    metrics: { tasksCompleted: 1200, accuracyScore: 99, avgLatencyMs: 60, confidenceAvg: 0.99 },
  },
  {
    id: 'orchestration.recovery',
    number: 19,
    name: 'Retry & Recovery Agent',
    title: 'Failure Recovery & Fallback Agent',
    category: 'orchestration',
    supervisorId: 'sup.orchestration',
    level: 3,
    description: 'Handles agent failures, executes exponential backoffs, triggers fallback agents, and manages replanning.',
    capabilities: ['circuit_breaking', 'fallback_agent_routing', 'graceful_degradation'],
    tools: ['circuit_breaker_registry', 'failure_root_cause_analyzer'],
    permissions: ['retry_tasks', 'reassign_failed_work', 'escalate_failures'],
    memoryScope: ['company_wide'],
    riskLevel: 'medium',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '🩹',
    metrics: { tasksCompleted: 140, accuracyScore: 96, avgLatencyMs: 340, confidenceAvg: 0.94 },
  },
  {
    id: 'orchestration.resource_allocation',
    number: 20,
    name: 'Resource Allocation Agent',
    title: 'Compute & Resource Allocation Agent',
    category: 'orchestration',
    supervisorId: 'sup.orchestration',
    level: 3,
    description: 'Allocates agents, tools, compute, LLM token quotas, and execution resources dynamically.',
    capabilities: ['token_quota_enforcement', 'rate_limiting', 'budget_allocation_per_pipeline'],
    tools: ['token_burn_rate_monitor', 'cloud_compute_allocator'],
    permissions: ['throttle_agent_concurrency', 'enforce_token_limits'],
    memoryScope: ['company_wide'],
    riskLevel: 'medium',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'fast_classifier',
    status: 'idle',
    avatarIcon: '📊',
    metrics: { tasksCompleted: 460, accuracyScore: 98, avgLatencyMs: 110, confidenceAvg: 0.97 },
  },

  // ==========================================
  // CATEGORY 3: ORGANIZATIONAL MEMORY & KNOWLEDGE (21-30)
  // ==========================================
  {
    id: 'memory.manager',
    number: 21,
    name: 'Memory Manager Agent',
    title: 'Organizational Memory Director Agent',
    category: 'memory',
    supervisorId: 'sup.memory',
    level: 2,
    description: 'Controls organizational memory architecture, indexing, storage policies, and unified recall.',
    capabilities: ['memory_federation', 'storage_lifecycle_management', 'retrieval_augmented_synthesis'],
    tools: ['vector_store_cluster', 'memory_tier_router', 'retention_policy_enforcer'],
    permissions: ['write_all_memory', 'purge_expired_memory', 'reindex_vector_embeddings'],
    memoryScope: ['company_wide'],
    riskLevel: 'medium',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '🧠',
    metrics: { tasksCompleted: 580, accuracyScore: 98, avgLatencyMs: 320, confidenceAvg: 0.97 },
  },
  {
    id: 'memory.episodic',
    number: 22,
    name: 'Episodic Memory Agent',
    title: 'Episodic & Experience Memory Agent',
    category: 'memory',
    supervisorId: 'sup.memory',
    level: 3,
    description: 'Stores important organizational events, previous incidents, project milestones, and historical experiences.',
    capabilities: ['event_chronology_recording', 'post_mortem_archiving', 'temporal_indexing'],
    tools: ['event_log_database', 'timeline_visualizer'],
    permissions: ['write_episodic_memory', 'query_event_history'],
    memoryScope: ['company_wide'],
    riskLevel: 'low',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'fast_classifier',
    status: 'idle',
    avatarIcon: '📜',
    metrics: { tasksCompleted: 390, accuracyScore: 97, avgLatencyMs: 180, confidenceAvg: 0.96 },
  },
  {
    id: 'memory.semantic',
    number: 23,
    name: 'Semantic Memory Agent',
    title: 'Semantic & Concepts Memory Agent',
    category: 'memory',
    supervisorId: 'sup.memory',
    level: 3,
    description: 'Stores reusable organizational concepts, business glossary, domain definitions, and institutional knowledge.',
    capabilities: ['ontology_curation', 'semantic_deduplication', 'entity_normalization'],
    tools: ['taxonomy_manager', 'semantic_embedding_index'],
    permissions: ['write_semantic_memory', 'update_glossary'],
    memoryScope: ['company_wide'],
    riskLevel: 'low',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '📚',
    metrics: { tasksCompleted: 410, accuracyScore: 98, avgLatencyMs: 250, confidenceAvg: 0.98 },
  },
  {
    id: 'memory.decision',
    number: 24,
    name: 'Decision Memory Agent',
    title: 'Decision Rationale & Alternatives Memory Agent',
    category: 'memory',
    supervisorId: 'sup.memory',
    level: 3,
    description: 'Stores historical company decisions, rationale, alternatives considered, trade-offs, and resulting outcomes.',
    capabilities: ['decision_record_structuring', 'rationale_extraction', 'counterfactual_logging'],
    tools: ['decision_log_db', 'adr_compiler'],
    permissions: ['write_decision_records', 'link_decision_outcomes'],
    memoryScope: ['company_wide', 'executive'],
    riskLevel: 'medium',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '⚖️',
    metrics: { tasksCompleted: 260, accuracyScore: 99, avgLatencyMs: 380, confidenceAvg: 0.98 },
  },
  {
    id: 'memory.policy',
    number: 25,
    name: 'Policy Memory Agent',
    title: 'Policy & Regulatory Rules Memory Agent',
    category: 'memory',
    supervisorId: 'sup.memory',
    level: 3,
    description: 'Stores organizational policies, operational guardrails, compliance rules, and ethical standards.',
    capabilities: ['policy_versioning', 'rule_conflict_identification', 'governance_rule_lookup'],
    tools: ['policy_rulebook_db', 'compliance_standard_indexer'],
    permissions: ['read_write_policies'],
    memoryScope: ['company_wide', 'legal'],
    riskLevel: 'medium',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'private_secure',
    status: 'idle',
    avatarIcon: '📋',
    metrics: { tasksCompleted: 190, accuracyScore: 99, avgLatencyMs: 290, confidenceAvg: 0.99 },
  },
  {
    id: 'memory.project',
    number: 26,
    name: 'Project Memory Agent',
    title: 'Project History & Artifact Memory Agent',
    category: 'memory',
    supervisorId: 'sup.memory',
    level: 3,
    description: 'Maintains project-specific history, deliverables, sprint goals, and initiative-level context.',
    capabilities: ['project_state_tracking', 'deliverable_indexing', 'scope_evolution_history'],
    tools: ['project_manifest_db', 'milestone_archive'],
    permissions: ['read_write_project_memory'],
    memoryScope: ['company_wide', 'product', 'engineering'],
    riskLevel: 'low',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'fast_classifier',
    status: 'idle',
    avatarIcon: '📁',
    metrics: { tasksCompleted: 340, accuracyScore: 97, avgLatencyMs: 210, confidenceAvg: 0.96 },
  },
  {
    id: 'memory.conversation',
    number: 27,
    name: 'Conversation Memory Agent',
    title: 'Agent & Human Dialogue Memory Agent',
    category: 'memory',
    supervisorId: 'sup.memory',
    level: 3,
    description: 'Maintains important multi-agent debates, executive meeting minutes, and human steering directives.',
    capabilities: ['dialogue_summarization', 'consensus_extraction', 'action_item_tagging'],
    tools: ['conversation_transcript_db', 'speaker_diarization_engine'],
    permissions: ['write_conversation_memory'],
    memoryScope: ['company_wide'],
    riskLevel: 'low',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'fast_classifier',
    status: 'idle',
    avatarIcon: '💬',
    metrics: { tasksCompleted: 450, accuracyScore: 96, avgLatencyMs: 310, confidenceAvg: 0.95 },
  },
  {
    id: 'memory.knowledge_graph',
    number: 28,
    name: 'Knowledge Graph Agent',
    title: 'Entity Relationship Knowledge Graph Agent',
    category: 'memory',
    supervisorId: 'sup.memory',
    level: 3,
    description: 'Maintains connected relationships between people, products, vendors, goals, risks, and systems.',
    capabilities: ['graph_traversal', 'multi_hop_inference', 'entity_resolution'],
    tools: ['neo4j_graph_querier', 'entity_extractor', 'cypher_generator'],
    permissions: ['read_write_graph_nodes'],
    memoryScope: ['company_wide'],
    riskLevel: 'medium',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '🕸️',
    metrics: { tasksCompleted: 520, accuracyScore: 98, avgLatencyMs: 410, confidenceAvg: 0.97 },
  },
  {
    id: 'memory.retrieval',
    number: 29,
    name: 'Memory Retrieval Agent',
    title: 'Contextual Memory Retrieval & Reranker Agent',
    category: 'memory',
    supervisorId: 'sup.memory',
    level: 3,
    description: 'Finds highly relevant historical context across all memory tiers using semantic search and cross-encoder reranking.',
    capabilities: ['hybrid_search', 'cross_encoder_reranking', 'recency_boost_weighting'],
    tools: ['bm25_vector_hybrid_querier', 'reranker_engine'],
    permissions: ['query_all_public_memory'],
    memoryScope: ['company_wide'],
    riskLevel: 'low',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'fast_classifier',
    status: 'idle',
    avatarIcon: '🔍',
    metrics: { tasksCompleted: 1100, accuracyScore: 99, avgLatencyMs: 140, confidenceAvg: 0.98 },
  },
  {
    id: 'memory.validation',
    number: 30,
    name: 'Memory Validation Agent',
    title: 'Memory Validator & Quality Auditor Agent',
    category: 'memory',
    supervisorId: 'sup.memory',
    level: 3,
    description: 'Detects outdated, contradictory, or unreliable memories before they pollute company context.',
    capabilities: ['fact_checking', 'contradiction_detection', 'hallucination_scrubbing'],
    tools: ['memory_consistency_checker', 'evidence_evaluator'],
    permissions: ['deprecate_invalid_memory', 'tag_memory_unverified'],
    memoryScope: ['company_wide'],
    riskLevel: 'medium',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '🔍',
    metrics: { tasksCompleted: 480, accuracyScore: 99, avgLatencyMs: 390, confidenceAvg: 0.99 },
  },

  // ==========================================
  // CATEGORY 4: STRATEGY & INTELLIGENCE (31-40)
  // ==========================================
  {
    id: 'strategy.market_intel',
    number: 31,
    name: 'Market Intelligence Agent',
    title: 'Market Intelligence & TAM Agent',
    category: 'strategy',
    supervisorId: 'sup.strategy',
    level: 3,
    description: 'Analyzes markets, target customer segments, macroeconomic signals, and growth vectors.',
    capabilities: ['tam_sam_som_modeling', 'macroeconomic_analysis', 'market_size_estimation'],
    tools: ['market_report_feed', 'industry_database_client', 'economic_indicator_api'],
    permissions: ['read_market_data', 'generate_market_reports'],
    memoryScope: ['strategy', 'company_wide'],
    riskLevel: 'medium',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '🌐',
    metrics: { tasksCompleted: 230, accuracyScore: 96, avgLatencyMs: 950, confidenceAvg: 0.94 },
  },
  {
    id: 'strategy.competitor_intel',
    number: 32,
    name: 'Competitor Intelligence Agent',
    title: 'Competitive Intelligence & Moat Agent',
    category: 'strategy',
    supervisorId: 'sup.strategy',
    level: 3,
    description: 'Analyzes competitors, feature parity, pricing moves, hiring trends, and competitive advantages.',
    capabilities: ['competitor_benchmarking', 'moat_durability_analysis', 'reverse_engineering_pricing'],
    tools: ['competitor_scraper_feed', 'patent_filing_db', 'job_posting_trend_analyzer'],
    permissions: ['read_competitor_data'],
    memoryScope: ['strategy', 'company_wide'],
    riskLevel: 'medium',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '🕵️',
    metrics: { tasksCompleted: 210, accuracyScore: 95, avgLatencyMs: 880, confidenceAvg: 0.93 },
  },
  {
    id: 'strategy.industry_trends',
    number: 33,
    name: 'Industry Trends Agent',
    title: 'Emerging Tech & Industry Trends Agent',
    category: 'strategy',
    supervisorId: 'sup.strategy',
    level: 3,
    description: 'Detects nascent industry trends, technological inflection points, and regulatory shifts.',
    capabilities: ['trend_extrapolation', 'weak_signal_detection', 'hype_cycle_positioning'],
    tools: ['arxiv_academic_feed', 'industry_news_crawler', 'trend_graph_analyzer'],
    permissions: ['read_industry_feeds'],
    memoryScope: ['strategy', 'company_wide'],
    riskLevel: 'low',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '📊',
    metrics: { tasksCompleted: 180, accuracyScore: 94, avgLatencyMs: 760, confidenceAvg: 0.91 },
  },
  {
    id: 'strategy.scenario_planning',
    number: 34,
    name: 'Scenario Planning Agent',
    title: 'Scenario & War Gaming Agent',
    category: 'strategy',
    supervisorId: 'sup.strategy',
    level: 3,
    description: 'Creates plausible future scenarios, stress-testing corporate strategies against adverse conditions.',
    capabilities: ['monte_carlo_scenarios', 'war_gaming_simulation', 'contingency_tree_generation'],
    tools: ['scenario_modeling_sandbox', 'probabilistic_forecast_tool'],
    permissions: ['run_scenario_simulations'],
    memoryScope: ['strategy', 'executive'],
    riskLevel: 'medium',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '🎲',
    metrics: { tasksCompleted: 160, accuracyScore: 95, avgLatencyMs: 1400, confidenceAvg: 0.92 },
  },
  {
    id: 'strategy.swot',
    number: 35,
    name: 'SWOT Agent',
    title: 'Strategic SWOT Analysis Agent',
    category: 'strategy',
    supervisorId: 'sup.strategy',
    level: 3,
    description: 'Performs rigorous Strengths, Weaknesses, Opportunities, and Threats cross-matrix analyses.',
    capabilities: ['swot_synthesis', 'tows_matrix_generation', 'internal_external_alignment'],
    tools: ['swot_matrix_generator', 'org_capability_registry'],
    permissions: ['read_all_department_summaries'],
    memoryScope: ['strategy', 'company_wide'],
    riskLevel: 'low',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '🗂️',
    metrics: { tasksCompleted: 195, accuracyScore: 96, avgLatencyMs: 650, confidenceAvg: 0.94 },
  },
  {
    id: 'strategy.strategic_planning',
    number: 36,
    name: 'Strategic Planning Agent',
    title: 'Corporate Long-Range Planning Agent',
    category: 'strategy',
    supervisorId: 'sup.strategy',
    level: 3,
    description: 'Creates cohesive multi-year strategic plans, resource allocation frameworks, and transformation roadmaps.',
    capabilities: ['long_range_roadmapping', 'strategic_initiative_scoping', 'okr_cascade'],
    tools: ['strategic_plan_builder', 'initiative_portfolio_tracker'],
    permissions: ['propose_strategic_plans'],
    memoryScope: ['strategy', 'executive'],
    riskLevel: 'high',
    autonomyLevel: 'level_3_approval_required',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '📐',
    metrics: { tasksCompleted: 145, accuracyScore: 97, avgLatencyMs: 1300, confidenceAvg: 0.95 },
  },
  {
    id: 'strategy.opportunity',
    number: 37,
    name: 'Opportunity Agent',
    title: 'New Market & Opportunity Discovery Agent',
    category: 'strategy',
    supervisorId: 'sup.strategy',
    level: 3,
    description: 'Identifies untapped customer segments, whitespace adjacencies, and high-margin monetization vectors.',
    capabilities: ['whitespace_mapping', 'business_model_innovation', 'revenue_expansion_scoring'],
    tools: ['customer_friction_index', 'adjacent_market_matrix'],
    permissions: ['propose_new_initiatives'],
    memoryScope: ['strategy', 'product'],
    riskLevel: 'medium',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '💡',
    metrics: { tasksCompleted: 170, accuracyScore: 93, avgLatencyMs: 820, confidenceAvg: 0.91 },
  },
  {
    id: 'strategy.threat_intel',
    number: 38,
    name: 'Threat Intelligence Agent',
    title: 'Strategic Threat & Disruption Agent',
    category: 'strategy',
    supervisorId: 'sup.strategy',
    level: 3,
    description: 'Identifies existential disruption risks, substitute products, predatory pricing, and regulatory traps.',
    capabilities: ['disruption_risk_scoring', 'vulnerability_radar', 'barrier_to_entry_decay_analysis'],
    tools: ['threat_feed_db', 'regulatory_filing_monitor'],
    permissions: ['flag_strategic_threats'],
    memoryScope: ['strategy', 'executive', 'security'],
    riskLevel: 'high',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '⚠️',
    metrics: { tasksCompleted: 190, accuracyScore: 98, avgLatencyMs: 910, confidenceAvg: 0.96 },
  },
  {
    id: 'strategy.innovation',
    number: 39,
    name: 'Innovation Agent',
    title: 'R&D & Business Model Innovation Agent',
    category: 'strategy',
    supervisorId: 'sup.strategy',
    level: 3,
    description: 'Proposes novel product paradigms, AI-native business processes, and non-linear technology bets.',
    capabilities: ['blue_ocean_ideation', 'emerging_tech_prototyping', 'patent_opportunity_scouting'],
    tools: ['innovation_pipeline_db', 'experiment_sandbox'],
    permissions: ['propose_r_and_d_bets'],
    memoryScope: ['strategy', 'product', 'engineering'],
    riskLevel: 'medium',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '✨',
    metrics: { tasksCompleted: 135, accuracyScore: 92, avgLatencyMs: 1100, confidenceAvg: 0.89 },
  },
  {
    id: 'strategy.strategic_decision',
    number: 40,
    name: 'Strategic Decision Agent',
    title: 'Strategic Synthesis & Recommendation Agent',
    category: 'strategy',
    supervisorId: 'sup.strategy',
    level: 3,
    description: 'Synthesizes multi-domain evidence, trade-offs, and critical debates into actionable executive recommendations.',
    capabilities: ['multi_criteria_decision_analysis', 'tradeoff_matrix_synthesis', 'executive_recommendation_authoring'],
    tools: ['mcda_decision_matrix', 'consensus_synthesis_engine'],
    permissions: ['author_decision_records'],
    memoryScope: ['strategy', 'executive', 'company_wide'],
    riskLevel: 'high',
    autonomyLevel: 'level_3_approval_required',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '🎯',
    metrics: { tasksCompleted: 210, accuracyScore: 98, avgLatencyMs: 1250, confidenceAvg: 0.97 },
  },

  // ==========================================
  // CATEGORY 5: FINANCE (41-50)
  // ==========================================
  {
    id: 'finance.financial_analysis',
    number: 41,
    name: 'Financial Analysis Agent',
    title: 'Financial Performance & Ratio Analysis Agent',
    category: 'finance',
    supervisorId: 'sup.finance',
    level: 3,
    description: 'Analyzes financial statements, EBITDA margins, operating leverage, and DuPont ratio decompositions.',
    capabilities: ['financial_statement_analysis', 'variance_analysis', 'dupont_breakdown'],
    tools: ['financial_ledger_querier', 'ratio_calculator'],
    permissions: ['read_financial_data'],
    memoryScope: ['finance'],
    riskLevel: 'medium',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '🧾',
    metrics: { tasksCompleted: 380, accuracyScore: 99, avgLatencyMs: 780, confidenceAvg: 0.98 },
  },
  {
    id: 'finance.budget',
    number: 42,
    name: 'Budget Agent',
    title: 'Departmental Budget & Variance Agent',
    category: 'finance',
    supervisorId: 'sup.finance',
    level: 3,
    description: 'Creates and monitors annual and quarterly departmental budgets, flagging overspend variances.',
    capabilities: ['budget_allocation', 'spend_tracking', 'burn_rate_anomaly_detection'],
    tools: ['erp_budget_module', 'spend_alert_system'],
    permissions: ['read_write_budgets'],
    memoryScope: ['finance', 'executive'],
    riskLevel: 'high',
    autonomyLevel: 'level_3_approval_required',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '💳',
    metrics: { tasksCompleted: 290, accuracyScore: 99, avgLatencyMs: 650, confidenceAvg: 0.99 },
  },
  {
    id: 'finance.forecast',
    number: 43,
    name: 'Forecast Agent',
    title: 'Rolling Financial Forecast Agent',
    category: 'finance',
    supervisorId: 'sup.finance',
    level: 3,
    description: 'Builds rolling P&L, balance sheet, and revenue forecasts under varying macroeconomic assumptions.',
    capabilities: ['arima_financial_forecasting', 'driver_based_planning', 'sensitivity_modeling'],
    tools: ['forecast_engine', 'time_series_forecaster'],
    permissions: ['read_financial_data', 'publish_forecasts'],
    memoryScope: ['finance', 'strategy'],
    riskLevel: 'high',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '📉',
    metrics: { tasksCompleted: 310, accuracyScore: 97, avgLatencyMs: 920, confidenceAvg: 0.95 },
  },
  {
    id: 'finance.cash_flow',
    number: 44,
    name: 'Cash Flow Agent',
    title: 'Working Capital & Cash Flow Agent',
    category: 'finance',
    supervisorId: 'sup.finance',
    level: 3,
    description: 'Tracks cash runway, collections cycle, DPO/DSO metrics, and short-term liquidity requirements.',
    capabilities: ['dcf_modeling', 'working_capital_optimization', 'runway_monitoring'],
    tools: ['bank_balance_querier', 'liquidity_forecast_tool'],
    permissions: ['read_cash_balances'],
    memoryScope: ['finance', 'executive'],
    riskLevel: 'critical',
    autonomyLevel: 'level_3_approval_required',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '💵',
    metrics: { tasksCompleted: 275, accuracyScore: 100, avgLatencyMs: 590, confidenceAvg: 0.99 },
  },
  {
    id: 'finance.revenue',
    number: 45,
    name: 'Revenue Agent',
    title: 'ARR & Revenue Recognition Agent',
    category: 'finance',
    supervisorId: 'sup.finance',
    level: 3,
    description: 'Analyzes recurring revenue (ARR/MRR), net revenue retention (NRR), and ASC 606 revenue compliance.',
    capabilities: ['asc_606_compliance', 'nrr_expansion_decomposition', 'churn_waterfall_analysis'],
    tools: ['stripe_billing_analytics', 'subscription_ledger'],
    permissions: ['read_revenue_streams'],
    memoryScope: ['finance', 'sales'],
    riskLevel: 'medium',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '💹',
    metrics: { tasksCompleted: 330, accuracyScore: 99, avgLatencyMs: 640, confidenceAvg: 0.98 },
  },
  {
    id: 'finance.cost',
    number: 46,
    name: 'Cost Agent',
    title: 'Cost Optimization & COGS Agent',
    category: 'finance',
    supervisorId: 'sup.finance',
    level: 3,
    description: 'Identifies vendor waste, cloud hosting over-provisioning, and margin optimization opportunities.',
    capabilities: ['cogs_reduction', 'cloud_finops_analysis', 'vendor_spend_consolidation'],
    tools: ['cloud_bill_analyzer', 'procurement_expense_audit'],
    permissions: ['audit_expenses', 'propose_cost_cuts'],
    memoryScope: ['finance', 'operations', 'engineering'],
    riskLevel: 'medium',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '✂️',
    metrics: { tasksCompleted: 360, accuracyScore: 98, avgLatencyMs: 710, confidenceAvg: 0.96 },
  },
  {
    id: 'finance.pricing',
    number: 47,
    name: 'Pricing Agent',
    title: 'Pricing Strategy & Elasticity Agent',
    category: 'finance',
    supervisorId: 'sup.finance',
    level: 3,
    description: 'Analyzes price elasticity of demand, value metric packaging, and tier monetization strategies.',
    capabilities: ['van_westendorp_pricing', 'conjoint_analysis', 'tier_packaging_optimization'],
    tools: ['pricing_simulation_engine', 'customer_wtp_database'],
    permissions: ['read_pricing_data', 'propose_price_changes'],
    memoryScope: ['finance', 'product', 'sales'],
    riskLevel: 'high',
    autonomyLevel: 'level_3_approval_required',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '🏷️',
    metrics: { tasksCompleted: 190, accuracyScore: 96, avgLatencyMs: 890, confidenceAvg: 0.94 },
  },
  {
    id: 'finance.investment',
    number: 48,
    name: 'Investment Agent',
    title: 'CapEx & M&A Investment Evaluator Agent',
    category: 'finance',
    supervisorId: 'sup.finance',
    level: 3,
    description: 'Evaluates capital investments, payback periods, internal rate of return (IRR), and M&A valuations.',
    capabilities: ['irr_npv_modeling', 'lbo_modeling', 'synergy_realization_tracking'],
    tools: ['m_and_a_valuation_suite', 'capex_roi_calculator'],
    permissions: ['evaluate_investment_proposals'],
    memoryScope: ['finance', 'executive', 'confidential'],
    riskLevel: 'critical',
    autonomyLevel: 'level_3_approval_required',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '🏛️',
    metrics: { tasksCompleted: 165, accuracyScore: 98, avgLatencyMs: 1350, confidenceAvg: 0.97 },
  },
  {
    id: 'finance.financial_risk',
    number: 49,
    name: 'Financial Risk Agent',
    title: 'FX, Credit & Solvency Risk Agent',
    category: 'finance',
    supervisorId: 'sup.finance',
    level: 3,
    description: 'Monitors foreign exchange exposure, customer credit default risk, interest rate sensitivity, and debt covenants.',
    capabilities: ['fx_hedging_strategy', 'counterparty_credit_risk', 'debt_covenant_stress_test'],
    tools: ['forex_exposure_monitor', 'credit_rating_feed'],
    permissions: ['read_financial_exposure', 'flag_risk_breaches'],
    memoryScope: ['finance', 'executive'],
    riskLevel: 'critical',
    autonomyLevel: 'level_3_approval_required',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '🚨',
    metrics: { tasksCompleted: 240, accuracyScore: 99, avgLatencyMs: 680, confidenceAvg: 0.98 },
  },
  {
    id: 'finance.cfo_reporting',
    number: 50,
    name: 'CFO Reporting Agent',
    title: 'Board & Executive Financial Reporting Agent',
    category: 'finance',
    supervisorId: 'sup.finance',
    level: 3,
    description: 'Synthesizes financial data into executive board decks, MD&A narratives, and investor updates.',
    capabilities: ['financial_storytelling', 'investor_deck_generation', 'board_kpi_dashboarding'],
    tools: ['financial_report_generator', 'sec_compliance_formatter'],
    permissions: ['generate_board_reports'],
    memoryScope: ['finance', 'executive'],
    riskLevel: 'high',
    autonomyLevel: 'level_3_approval_required',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '📑',
    metrics: { tasksCompleted: 210, accuracyScore: 99, avgLatencyMs: 920, confidenceAvg: 0.98 },
  },

  // ==========================================
  // CATEGORY 6: SALES & MARKETING (51-60)
  // ==========================================
  {
    id: 'sales_marketing.sales_strategy',
    number: 51,
    name: 'Sales Strategy Agent',
    title: 'Enterprise Go-To-Market Sales Strategy Agent',
    category: 'sales_marketing',
    supervisorId: 'sup.sales',
    level: 3,
    description: 'Defines sales methodology (MEDDPICC), territory allocations, commission structures, and deal playbooks.',
    capabilities: ['meddpicc_qualification_framework', 'territory_planning', 'win_loss_analysis'],
    tools: ['sales_playbook_db', 'quota_distribution_tool'],
    permissions: ['read_write_sales_strategy'],
    memoryScope: ['sales', 'executive'],
    riskLevel: 'medium',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '🎯',
    metrics: { tasksCompleted: 240, accuracyScore: 96, avgLatencyMs: 760, confidenceAvg: 0.94 },
  },
  {
    id: 'sales_marketing.lead_research',
    number: 52,
    name: 'Lead Research Agent',
    title: 'Prospect & Account Research Agent',
    category: 'sales_marketing',
    supervisorId: 'sup.sales',
    level: 3,
    description: 'Enriches account firmographics, identifies key decision makers, and compiles technographic profiles.',
    capabilities: ['account_intelligence', 'org_chart_mapping', 'intent_signal_extraction'],
    tools: ['clearbit_firmographic_api', 'linkedin_sales_nav_crawler', 'technographic_scanner'],
    permissions: ['query_lead_databases'],
    memoryScope: ['sales'],
    riskLevel: 'low',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'fast_classifier',
    status: 'idle',
    avatarIcon: '🔎',
    metrics: { tasksCompleted: 890, accuracyScore: 97, avgLatencyMs: 310, confidenceAvg: 0.96 },
  },
  {
    id: 'sales_marketing.lead_qualification',
    number: 53,
    name: 'Lead Qualification Agent',
    title: 'Predictive Lead Scoring Agent',
    category: 'sales_marketing',
    supervisorId: 'sup.sales',
    level: 3,
    description: 'Scores inbound and outbound leads based on ideal customer profile (ICP) match and behavioral signals.',
    capabilities: ['icp_scoring_algorithm', 'bant_assessment', 'conversion_probability_ranking'],
    tools: ['lead_scoring_model', 'intent_data_stream'],
    permissions: ['modify_lead_status'],
    memoryScope: ['sales'],
    riskLevel: 'low',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'fast_classifier',
    status: 'idle',
    avatarIcon: '⭐',
    metrics: { tasksCompleted: 1150, accuracyScore: 98, avgLatencyMs: 150, confidenceAvg: 0.97 },
  },
  {
    id: 'sales_marketing.crm',
    number: 54,
    name: 'CRM Agent',
    title: 'CRM Automation & Data Hygiene Agent',
    category: 'sales_marketing',
    supervisorId: 'sup.sales',
    level: 3,
    description: 'Maintains CRM data cleanliness, logs sales interactions, and triggers lifecycle stage transitions.',
    capabilities: ['crm_synchronization', 'record_deduplication', 'stage_progression_automation'],
    tools: ['salesforce_hubspot_api', 'crm_data_hygiene_checker'],
    permissions: ['read_write_crm_records'],
    memoryScope: ['sales'],
    riskLevel: 'low',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'fast_classifier',
    status: 'idle',
    avatarIcon: '🗄️',
    metrics: { tasksCompleted: 980, accuracyScore: 99, avgLatencyMs: 190, confidenceAvg: 0.99 },
  },
  {
    id: 'sales_marketing.sales_pipeline',
    number: 55,
    name: 'Sales Pipeline Agent',
    title: 'Pipeline Velocity & Deal Health Agent',
    category: 'sales_marketing',
    supervisorId: 'sup.sales',
    level: 3,
    description: 'Monitors deal slippage, stage dwell time, close rates, and overall sales pipeline health.',
    capabilities: ['deal_slippage_forecasting', 'pipeline_velocity_calculation', 'pipeline_coverage_audit'],
    tools: ['pipeline_analytics_view', 'deal_risk_detector'],
    permissions: ['read_sales_pipeline'],
    memoryScope: ['sales', 'executive'],
    riskLevel: 'medium',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '📊',
    metrics: { tasksCompleted: 410, accuracyScore: 97, avgLatencyMs: 510, confidenceAvg: 0.95 },
  },
  {
    id: 'sales_marketing.marketing_strategy',
    number: 56,
    name: 'Marketing Strategy Agent',
    title: 'Integrated Marketing Strategy Agent',
    category: 'sales_marketing',
    supervisorId: 'sup.marketing',
    level: 3,
    description: 'Defines target personas, value pillars, channel mix strategy, and marketing funnel architecture.',
    capabilities: ['persona_definition', 'channel_mix_optimization', 'full_funnel_attribution'],
    tools: ['marketing_mix_model', 'persona_database'],
    permissions: ['read_write_marketing_plans'],
    memoryScope: ['marketing', 'company_wide'],
    riskLevel: 'medium',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '📣',
    metrics: { tasksCompleted: 260, accuracyScore: 95, avgLatencyMs: 690, confidenceAvg: 0.93 },
  },
  {
    id: 'sales_marketing.campaign',
    number: 57,
    name: 'Campaign Agent',
    title: 'Multichannel Campaign Management Agent',
    category: 'sales_marketing',
    supervisorId: 'sup.marketing',
    level: 3,
    description: 'Plans, schedules, and optimizes paid, organic, email, and social acquisition campaigns.',
    capabilities: ['campaign_calendar_orchestration', 'a_b_experiment_design', 'budget_pacing'],
    tools: ['ad_platform_manager', 'email_campaign_tool'],
    permissions: ['manage_campaigns', 'adjust_ad_spends'],
    memoryScope: ['marketing'],
    riskLevel: 'medium',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '🚀',
    metrics: { tasksCompleted: 370, accuracyScore: 96, avgLatencyMs: 480, confidenceAvg: 0.94 },
  },
  {
    id: 'sales_marketing.content',
    number: 58,
    name: 'Content Agent',
    title: 'Editorial & Brand Content Agent',
    category: 'sales_marketing',
    supervisorId: 'sup.marketing',
    level: 3,
    description: 'Creates thought leadership articles, case studies, product documentation, and viral social assets.',
    capabilities: ['seo_optimized_copywriting', 'thought_leadership_authoring', 'brand_voice_compliance'],
    tools: ['cms_publisher', 'seo_keyword_analyzer', 'readability_scorer'],
    permissions: ['publish_draft_content'],
    memoryScope: ['marketing'],
    riskLevel: 'low',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '✍️',
    metrics: { tasksCompleted: 530, accuracyScore: 97, avgLatencyMs: 620, confidenceAvg: 0.96 },
  },
  {
    id: 'sales_marketing.customer_acquisition',
    number: 59,
    name: 'Customer Acquisition Agent',
    title: 'Paid Media & CAC Optimization Agent',
    category: 'sales_marketing',
    supervisorId: 'sup.marketing',
    level: 3,
    description: 'Optimizes blended Customer Acquisition Cost (CAC), payback periods, and conversion rate funnels.',
    capabilities: ['cac_ltv_optimization', 'cro_funnel_auditing', 'bid_strategy_tuning'],
    tools: ['analytics_funnel_tracker', 'conversion_optimizer'],
    permissions: ['read_ad_spend', 'propose_bid_adjustments'],
    memoryScope: ['marketing', 'finance'],
    riskLevel: 'medium',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'fast_classifier',
    status: 'idle',
    avatarIcon: '🧲',
    metrics: { tasksCompleted: 440, accuracyScore: 98, avgLatencyMs: 380, confidenceAvg: 0.97 },
  },
  {
    id: 'sales_marketing.growth',
    number: 60,
    name: 'Growth Agent',
    title: 'Product-Led Growth & Virality Agent',
    category: 'sales_marketing',
    supervisorId: 'sup.marketing',
    level: 3,
    description: 'Designs referral loops, onboarding aha-moments, viral distribution loops, and self-serve expansions.',
    capabilities: ['plg_loop_design', 'referral_mechanism_engineering', 'activation_rate_optimization'],
    tools: ['growth_experiment_sandbox', 'product_telemetry_feed'],
    permissions: ['propose_growth_experiments'],
    memoryScope: ['marketing', 'product'],
    riskLevel: 'medium',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '🌱',
    metrics: { tasksCompleted: 310, accuracyScore: 95, avgLatencyMs: 740, confidenceAvg: 0.93 },
  },

  // ==========================================
  // CATEGORY 7: PRODUCT & ENGINEERING (61-70)
  // ==========================================
  {
    id: 'product_engineering.product_strategy',
    number: 61,
    name: 'Product Strategy Agent',
    title: 'Product Vision & Strategy Agent',
    category: 'product_engineering',
    supervisorId: 'sup.product',
    level: 3,
    description: 'Formulates product core value propositions, feature differentiation, and user retention engines.',
    capabilities: ['product_differentiation', 'value_metric_selection', 'feature_tiering'],
    tools: ['product_vision_doc_builder', 'feature_prioritization_matrix'],
    permissions: ['write_product_strategy'],
    memoryScope: ['product', 'company_wide'],
    riskLevel: 'medium',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '💡',
    metrics: { tasksCompleted: 270, accuracyScore: 96, avgLatencyMs: 810, confidenceAvg: 0.94 },
  },
  {
    id: 'product_engineering.product_research',
    number: 62,
    name: 'Product Research Agent',
    title: 'User & Market Needs Research Agent',
    category: 'product_engineering',
    supervisorId: 'sup.product',
    level: 3,
    description: 'Synthesizes qualitative customer interviews, survey data, and usability feedback into user insights.',
    capabilities: ['jobs_to_be_done_mapping', 'user_interview_synthesis', 'sentiment_clustering'],
    tools: ['user_research_repository', 'interview_transcript_analyzer'],
    permissions: ['read_user_feedback'],
    memoryScope: ['product', 'customer'],
    riskLevel: 'low',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '🔍',
    metrics: { tasksCompleted: 350, accuracyScore: 96, avgLatencyMs: 540, confidenceAvg: 0.95 },
  },
  {
    id: 'product_engineering.requirements',
    number: 63,
    name: 'Requirements Agent',
    title: 'PRD & Functional Specifications Agent',
    category: 'product_engineering',
    supervisorId: 'sup.product',
    level: 3,
    description: 'Translates high-level business goals into rigorous Product Requirement Documents (PRDs) and user stories.',
    capabilities: ['prd_generation', 'acceptance_criteria_authoring', 'edge_case_specification'],
    tools: ['prd_generator_tool', 'jira_story_sync'],
    permissions: ['create_user_stories', 'write_prds'],
    memoryScope: ['product', 'engineering'],
    riskLevel: 'low',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '📝',
    metrics: { tasksCompleted: 490, accuracyScore: 98, avgLatencyMs: 610, confidenceAvg: 0.97 },
  },
  {
    id: 'product_engineering.roadmap',
    number: 64,
    name: 'Roadmap Agent',
    title: 'Release & Horizon Roadmap Agent',
    category: 'product_engineering',
    supervisorId: 'sup.product',
    level: 3,
    description: 'Balances feature delivery timelines, engineering capacity, technical debt, and business milestones.',
    capabilities: ['roadmap_sequencing', 'wsjf_prioritization', 'capacity_burnup_planning'],
    tools: ['interactive_roadmap_canvas', 'sprint_capacity_calculator'],
    permissions: ['modify_product_roadmap'],
    memoryScope: ['product', 'engineering'],
    riskLevel: 'medium',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '🗺️',
    metrics: { tasksCompleted: 310, accuracyScore: 97, avgLatencyMs: 720, confidenceAvg: 0.95 },
  },
  {
    id: 'product_engineering.ux',
    number: 65,
    name: 'UX Agent',
    title: 'User Experience & Information Architecture Agent',
    category: 'product_engineering',
    supervisorId: 'sup.product',
    level: 3,
    description: 'Analyzes user interaction flows, accessibility (WCAG 2.1), micro-interactions, and cognitive load.',
    capabilities: ['wireframe_spec_generation', 'cognitive_walkthrough', 'wcag_accessibility_audit'],
    tools: ['design_system_component_library', 'flowchart_generator'],
    permissions: ['generate_ux_specs'],
    memoryScope: ['product'],
    riskLevel: 'low',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '🎨',
    metrics: { tasksCompleted: 380, accuracyScore: 97, avgLatencyMs: 650, confidenceAvg: 0.96 },
  },
  {
    id: 'product_engineering.architecture',
    number: 66,
    name: 'Architecture Agent',
    title: 'Systems & Cloud Architecture Agent',
    category: 'product_engineering',
    supervisorId: 'sup.engineering',
    level: 3,
    description: 'Designs distributed systems, event-driven backends, database schemas, and microservice boundaries.',
    capabilities: ['event_driven_design', 'database_sharding_indexing', 'adr_documentation'],
    tools: ['system_architecture_diagrammer', 'database_schema_validator'],
    permissions: ['write_architecture_adrs'],
    memoryScope: ['engineering'],
    riskLevel: 'high',
    autonomyLevel: 'level_3_approval_required',
    defaultModel: 'code_optimizer',
    status: 'idle',
    avatarIcon: '🏗️',
    metrics: { tasksCompleted: 340, accuracyScore: 99, avgLatencyMs: 890, confidenceAvg: 0.98 },
  },
  {
    id: 'product_engineering.coding',
    number: 67,
    name: 'Coding Agent',
    title: 'Full-Stack Implementation Agent',
    category: 'product_engineering',
    supervisorId: 'sup.engineering',
    level: 3,
    description: 'Writes production-grade TypeScript, Python, and SQL code adhering to clean architecture principles.',
    capabilities: ['type_safe_programming', 'refactoring', 'api_endpoint_generation'],
    tools: ['git_repo_workspace', 'ast_linter_tool', 'code_sandbox_runner'],
    permissions: ['commit_code_branches', 'create_pull_requests'],
    memoryScope: ['engineering'],
    riskLevel: 'medium',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'code_optimizer',
    status: 'idle',
    avatarIcon: '💻',
    metrics: { tasksCompleted: 920, accuracyScore: 98, avgLatencyMs: 1100, confidenceAvg: 0.97 },
  },
  {
    id: 'product_engineering.testing',
    number: 68,
    name: 'Testing Agent',
    title: 'Automated QA & Security Test Agent',
    category: 'product_engineering',
    supervisorId: 'sup.engineering',
    level: 3,
    description: 'Generates unit, integration, mutation, and end-to-end regression test suites.',
    capabilities: ['e2e_playwright_testing', 'mutation_testing', 'edge_case_fuzzing'],
    tools: ['test_runner_sandbox', 'code_coverage_reporter'],
    permissions: ['execute_test_suites', 'block_flaky_deployments'],
    memoryScope: ['engineering'],
    riskLevel: 'low',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'code_optimizer',
    status: 'idle',
    avatarIcon: '🧪',
    metrics: { tasksCompleted: 870, accuracyScore: 99, avgLatencyMs: 490, confidenceAvg: 0.99 },
  },
  {
    id: 'product_engineering.devops',
    number: 69,
    name: 'DevOps Agent',
    title: 'CI/CD & Infrastructure Automation Agent',
    category: 'product_engineering',
    supervisorId: 'sup.engineering',
    level: 3,
    description: 'Manages Kubernetes clusters, Terraform IaC, blue-green deployments, and observability stacks.',
    capabilities: ['kubernetes_manifest_generation', 'canary_deployment_management', 'incident_auto_remediation'],
    tools: ['cloud_provider_api', 'github_actions_client', 'prometheus_grafana_query'],
    permissions: ['trigger_deployments', 'scale_compute_nodes'],
    riskLevel: 'critical',
    autonomyLevel: 'level_3_approval_required',
    defaultModel: 'code_optimizer',
    status: 'idle',
    avatarIcon: '🚀',
    metrics: { tasksCompleted: 460, accuracyScore: 99, avgLatencyMs: 580, confidenceAvg: 0.98 },
  },
  {
    id: 'product_engineering.tech_debt',
    number: 70,
    name: 'Technical Debt Agent',
    title: 'Code Health & Tech Debt Prioritization Agent',
    category: 'product_engineering',
    supervisorId: 'sup.engineering',
    level: 3,
    description: 'Tracks architectural decay, outdated dependencies, cyclomatic complexity, and refactoring ROI.',
    capabilities: ['sonarqube_analysis', 'dependency_vulnerability_scan', 'refactoring_roi_scoring'],
    tools: ['codebase_complexity_scanner', 'tech_debt_backlog_db'],
    permissions: ['flag_tech_debt_items'],
    memoryScope: ['engineering'],
    riskLevel: 'low',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'code_optimizer',
    status: 'idle',
    avatarIcon: '🧹',
    metrics: { tasksCompleted: 390, accuracyScore: 98, avgLatencyMs: 420, confidenceAvg: 0.97 },
  },

  // ==========================================
  // CATEGORY 8: OPERATIONS & SUPPLY CHAIN (71-80)
  // ==========================================
  {
    id: 'operations.operations',
    number: 71,
    name: 'Operations Agent',
    title: 'Core Business Operations Agent',
    category: 'operations',
    supervisorId: 'sup.operations',
    level: 3,
    description: 'Manages operational cadence, business rhythm, resource allocation, and daily execution metrics.',
    capabilities: ['daily_ops_monitoring', 'cross_silo_sync', 'sla_enforcement'],
    tools: ['ops_command_center_view', 'sla_tracker'],
    permissions: ['read_write_operations'],
    memoryScope: ['operations'],
    riskLevel: 'medium',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '⚙️',
    metrics: { tasksCompleted: 510, accuracyScore: 97, avgLatencyMs: 410, confidenceAvg: 0.96 },
  },
  {
    id: 'operations.process_opt',
    number: 72,
    name: 'Process Optimization Agent',
    title: 'Six Sigma & Process Optimization Agent',
    category: 'operations',
    supervisorId: 'sup.operations',
    level: 3,
    description: 'Identifies cycle time waste, handoff friction, and automates manual business workflows.',
    capabilities: ['value_stream_mapping', 'bottleneck_root_cause_analysis', 'lean_workflow_redesign'],
    tools: ['process_mining_tool', 'cycle_time_simulator'],
    permissions: ['propose_process_modifications'],
    memoryScope: ['operations', 'company_wide'],
    riskLevel: 'low',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '⚡',
    metrics: { tasksCompleted: 320, accuracyScore: 98, avgLatencyMs: 610, confidenceAvg: 0.97 },
  },
  {
    id: 'operations.workflow',
    number: 73,
    name: 'Workflow Agent',
    title: 'SOP & Workflow Automation Agent',
    category: 'operations',
    supervisorId: 'sup.operations',
    level: 3,
    description: 'Designs and executes standard operating procedures (SOPs), RPA triggers, and escalation logic.',
    capabilities: ['sop_generation', 'bpmn_workflow_authoring', 'exception_escalation'],
    tools: ['sop_repository_db', 'workflow_engine_integrator'],
    permissions: ['publish_sops', 'trigger_rpa_tasks'],
    memoryScope: ['operations'],
    riskLevel: 'low',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'fast_classifier',
    status: 'idle',
    avatarIcon: '🔄',
    metrics: { tasksCompleted: 640, accuracyScore: 99, avgLatencyMs: 220, confidenceAvg: 0.98 },
  },
  {
    id: 'operations.procurement',
    number: 74,
    name: 'Procurement Agent',
    title: 'Procurement & Contract Negotiation Agent',
    category: 'operations',
    supervisorId: 'sup.operations',
    level: 3,
    description: 'Evaluates vendor proposals, analyzes contract terms, benchmarks pricing, and issues purchase orders.',
    capabilities: ['rfp_generation_evaluation', 'vendor_rate_benchmarking', 'sla_terms_review'],
    tools: ['procurement_portal_api', 'contract_pricing_comparator'],
    permissions: ['read_vendor_contracts', 'draft_pos'],
    memoryScope: ['operations', 'finance'],
    riskLevel: 'high',
    autonomyLevel: 'level_3_approval_required',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '📦',
    metrics: { tasksCompleted: 240, accuracyScore: 97, avgLatencyMs: 830, confidenceAvg: 0.95 },
  },
  {
    id: 'operations.supplier',
    number: 75,
    name: 'Supplier Agent',
    title: 'Supplier Relationship & Tiering Agent',
    category: 'operations',
    supervisorId: 'sup.operations',
    level: 3,
    description: 'Assesses supplier reliability, geopolitical exposure, ESG compliance, and tier-2 vendor risks.',
    capabilities: ['supplier_scorecarding', 'single_source_dependency_check', 'esg_compliance_audit'],
    tools: ['supplier_risk_db', 'vendor_performance_matrix'],
    permissions: ['read_supplier_profiles'],
    memoryScope: ['operations'],
    riskLevel: 'medium',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '🏭',
    metrics: { tasksCompleted: 210, accuracyScore: 96, avgLatencyMs: 740, confidenceAvg: 0.94 },
  },
  {
    id: 'operations.inventory',
    number: 76,
    name: 'Inventory Agent',
    title: 'Inventory & Stock Intelligence Agent',
    category: 'operations',
    supervisorId: 'sup.operations',
    level: 3,
    description: 'Maintains optimal safety stock, calculates Economic Order Quantity (EOQ), and prevents stockouts.',
    capabilities: ['eoq_calculation', 'safety_stock_optimization', 'obsolescence_forecasting'],
    tools: ['warehouse_inventory_db', 'inventory_turnover_calculator'],
    permissions: ['read_stock_levels', 'propose_reorder_triggers'],
    memoryScope: ['operations'],
    riskLevel: 'low',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'fast_classifier',
    status: 'idle',
    avatarIcon: '🏢',
    metrics: { tasksCompleted: 430, accuracyScore: 99, avgLatencyMs: 290, confidenceAvg: 0.98 },
  },
  {
    id: 'operations.logistics',
    number: 77,
    name: 'Logistics Agent',
    title: 'Freight & Route Optimization Agent',
    category: 'operations',
    supervisorId: 'sup.operations',
    level: 3,
    description: 'Optimizes distribution networks, 3PL carrier contracts, fuel surcharges, and customs clearance.',
    capabilities: ['freight_rate_optimization', 'carrier_performance_tracking', 'customs_tariff_lookup'],
    tools: ['logistics_route_solver', 'freight_tracking_api'],
    permissions: ['read_freight_rates'],
    memoryScope: ['operations'],
    riskLevel: 'low',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'fast_classifier',
    status: 'idle',
    avatarIcon: '🚚',
    metrics: { tasksCompleted: 390, accuracyScore: 97, avgLatencyMs: 310, confidenceAvg: 0.96 },
  },
  {
    id: 'operations.demand_forecast',
    number: 78,
    name: 'Demand Forecast Agent',
    title: 'Demand & Production Forecasting Agent',
    category: 'operations',
    supervisorId: 'sup.operations',
    level: 3,
    description: 'Forecasts customer order volume, seasonality spikes, and capacity constraints across regions.',
    capabilities: ['seasonality_decomposition', 'demand_sensing', 'capacity_headroom_analysis'],
    tools: ['demand_modeling_suite', 'sales_seasonality_analyzer'],
    permissions: ['publish_demand_forecasts'],
    memoryScope: ['operations', 'sales'],
    riskLevel: 'medium',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '📈',
    metrics: { tasksCompleted: 310, accuracyScore: 96, avgLatencyMs: 690, confidenceAvg: 0.94 },
  },
  {
    id: 'operations.quality_ops',
    number: 79,
    name: 'Quality Operations Agent',
    title: 'Quality Assurance & Incident Review Agent',
    category: 'operations',
    supervisorId: 'sup.operations',
    level: 3,
    description: 'Monitors operational defect rates, customer return RMA trends, and conducts 5-Why root cause investigations.',
    capabilities: ['five_why_investigation', 'defect_rate_spc_charting', 'rma_trend_clustering'],
    tools: ['quality_incident_db', 'spc_control_chart_generator'],
    permissions: ['log_quality_incidents'],
    memoryScope: ['operations'],
    riskLevel: 'medium',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '🛡️',
    metrics: { tasksCompleted: 280, accuracyScore: 98, avgLatencyMs: 510, confidenceAvg: 0.97 },
  },
  {
    id: 'operations.business_continuity',
    number: 80,
    name: 'Business Continuity Agent',
    title: 'Disaster Recovery & Crisis Contingency Agent',
    category: 'operations',
    supervisorId: 'sup.operations',
    level: 3,
    description: 'Maintains Business Impact Analyses (BIA), disaster recovery plans, backup failovers, and crisis playbooks.',
    capabilities: ['business_impact_analysis', 'dr_playbook_generation', 'crisis_communication_tree'],
    tools: ['continuity_playbook_db', 'emergency_alert_system'],
    permissions: ['trigger_dr_drills', 'broadcast_crisis_alerts'],
    memoryScope: ['operations', 'executive', 'security'],
    riskLevel: 'critical',
    autonomyLevel: 'level_3_approval_required',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '🚨',
    metrics: { tasksCompleted: 140, accuracyScore: 99, avgLatencyMs: 820, confidenceAvg: 0.98 },
  },

  // ==========================================
  // CATEGORY 9: PEOPLE & HR (81-87)
  // ==========================================
  {
    id: 'people_hr.talent',
    number: 81,
    name: 'Talent Agent',
    title: 'Strategic Talent & Capability Agent',
    category: 'people_hr',
    supervisorId: 'sup.hr',
    level: 3,
    description: 'Defines competency matrices, career progression ladders, and strategic skill-gap roadmaps.',
    capabilities: ['skills_ontology_mapping', 'competency_framework_design', 'succession_readiness_scoring'],
    tools: ['skills_matrix_db', 'career_ladder_repository'],
    permissions: ['read_write_talent_frameworks'],
    memoryScope: ['hr'],
    riskLevel: 'low',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '🌟',
    metrics: { tasksCompleted: 230, accuracyScore: 96, avgLatencyMs: 540, confidenceAvg: 0.94 },
  },
  {
    id: 'people_hr.recruiting',
    number: 82,
    name: 'Recruiting Agent',
    title: 'Candidate Sourcing & Screening Agent',
    category: 'people_hr',
    supervisorId: 'sup.hr',
    level: 3,
    description: 'Generates job descriptions, screens incoming resumes, schedules interview loops, and analyzes candidate scorecards.',
    capabilities: ['resume_parsing_ranking', 'structured_interview_design', 'candidate_scorecard_aggregation'],
    tools: ['ats_greenhouse_api', 'jd_generator_tool'],
    permissions: ['read_write_candidate_data'],
    memoryScope: ['hr'],
    riskLevel: 'medium',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'fast_classifier',
    status: 'idle',
    avatarIcon: '🎯',
    metrics: { tasksCompleted: 610, accuracyScore: 97, avgLatencyMs: 290, confidenceAvg: 0.95 },
  },
  {
    id: 'people_hr.onboarding',
    number: 83,
    name: 'Onboarding Agent',
    title: 'New Hire Ramp-Up & Onboarding Agent',
    category: 'people_hr',
    supervisorId: 'sup.hr',
    level: 3,
    description: 'Orchestrates 30-60-90 day onboarding milestones, system access provisioning, and orientation schedules.',
    capabilities: ['onboarding_checklist_automation', 'time_to_productivity_monitoring', 'buddy_assignment_matcher'],
    tools: ['onboarding_portal_db', 'access_provisioning_queue'],
    permissions: ['manage_onboarding_plans'],
    memoryScope: ['hr'],
    riskLevel: 'low',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'fast_classifier',
    status: 'idle',
    avatarIcon: '🚀',
    metrics: { tasksCompleted: 450, accuracyScore: 99, avgLatencyMs: 180, confidenceAvg: 0.98 },
  },
  {
    id: 'people_hr.learning',
    number: 84,
    name: 'Learning Agent',
    title: 'L&D & Organizational Upskilling Agent',
    category: 'people_hr',
    supervisorId: 'sup.hr',
    level: 3,
    description: 'Creates customized training curriculums, AI literacy workshops, and tracks certification compliance.',
    capabilities: ['curriculum_generation', 'skill_assessment_design', 'learning_path_personalization'],
    tools: ['lms_curriculum_builder', 'training_completion_tracker'],
    permissions: ['publish_courses'],
    memoryScope: ['hr'],
    riskLevel: 'low',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '📖',
    metrics: { tasksCompleted: 310, accuracyScore: 97, avgLatencyMs: 480, confidenceAvg: 0.96 },
  },
  {
    id: 'people_hr.performance',
    number: 85,
    name: 'Performance Agent',
    title: 'Performance Review & OKR Calibration Agent',
    category: 'people_hr',
    supervisorId: 'sup.hr',
    level: 3,
    description: 'Calibrates 360-degree reviews, aligns goal achievements, and identifies high-potential talent.',
    capabilities: ['performance_distribution_calibration', 'okr_achievement_scoring', 'bias_free_review_auditing'],
    tools: ['performance_review_db', '9_box_talent_grid'],
    permissions: ['read_confidential_people_data'],
    memoryScope: ['hr', 'executive', 'confidential'],
    riskLevel: 'high',
    autonomyLevel: 'level_3_approval_required',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '📊',
    metrics: { tasksCompleted: 260, accuracyScore: 98, avgLatencyMs: 720, confidenceAvg: 0.97 },
  },
  {
    id: 'people_hr.workforce_planning',
    number: 86,
    name: 'Workforce Planning Agent',
    title: 'Headcount & Capacity Planning Agent',
    category: 'people_hr',
    supervisorId: 'sup.hr',
    level: 3,
    description: 'Forecasts organizational headcount requirements, attrition probabilities, and wage band benchmarks.',
    capabilities: ['attrition_predictive_modeling', 'headcount_capacity_reconciliation', 'compensation_band_modeling'],
    tools: ['headcount_forecast_tool', 'comp_market_benchmark_db'],
    permissions: ['read_write_headcount_plans'],
    memoryScope: ['hr', 'finance', 'executive'],
    riskLevel: 'high',
    autonomyLevel: 'level_3_approval_required',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '👥',
    metrics: { tasksCompleted: 220, accuracyScore: 97, avgLatencyMs: 840, confidenceAvg: 0.95 },
  },
  {
    id: 'people_hr.culture',
    number: 87,
    name: 'Culture Agent',
    title: 'Organizational Health & Culture Agent',
    category: 'people_hr',
    supervisorId: 'sup.hr',
    level: 3,
    description: 'Analyzes organizational network graph dynamics, cross-team silos, eNPS sentiment, and burnout risks.',
    capabilities: ['enps_sentiment_analysis', 'organizational_network_analysis', 'burnout_early_warning_detection'],
    tools: ['employee_sentiment_analyzer', 'collaboration_network_graph'],
    permissions: ['read_anonymous_pulse_data'],
    memoryScope: ['hr', 'company_wide'],
    riskLevel: 'low',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '❤️',
    metrics: { tasksCompleted: 190, accuracyScore: 95, avgLatencyMs: 510, confidenceAvg: 0.94 },
  },

  // ==========================================
  // CATEGORY 10: LEGAL, SECURITY & GOVERNANCE (88-95)
  // ==========================================
  {
    id: 'legal_governance.legal',
    number: 88,
    name: 'Legal Agent',
    title: 'Corporate Counsel & Legal Research Agent',
    category: 'legal_governance',
    supervisorId: 'sup.legal',
    level: 3,
    description: 'Performs legal risk assessments, contract clause reviews (indemnities, IP ownership, liability caps), and legal research.',
    capabilities: ['contract_clause_redlining', 'legal_precedent_research', 'ip_assignment_verification'],
    tools: ['legal_corpus_database', 'contract_analyzer_suite'],
    permissions: ['read_legal_contracts', 'flag_legal_liabilities'],
    memoryScope: ['legal', 'executive', 'confidential'],
    riskLevel: 'critical',
    autonomyLevel: 'level_3_approval_required',
    defaultModel: 'private_secure',
    status: 'idle',
    avatarIcon: '⚖️',
    metrics: { tasksCompleted: 340, accuracyScore: 99, avgLatencyMs: 980, confidenceAvg: 0.98 },
  },
  {
    id: 'legal_governance.compliance',
    number: 89,
    name: 'Compliance Agent',
    title: 'Regulatory & Industry Compliance Agent',
    category: 'legal_governance',
    supervisorId: 'sup.governance',
    level: 3,
    description: 'Checks compliance against SOC 2 Type II, ISO 27001, HIPAA, GDPR, and industry regulatory frameworks.',
    capabilities: ['soc2_control_mapping', 'gap_analysis_against_iso27001', 'audit_evidence_collector'],
    tools: ['compliance_control_register', 'regulatory_framework_index'],
    permissions: ['audit_all_systems', 'flag_compliance_violations'],
    memoryScope: ['legal', 'security', 'company_wide'],
    riskLevel: 'high',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'private_secure',
    status: 'idle',
    avatarIcon: '🛡️',
    metrics: { tasksCompleted: 420, accuracyScore: 100, avgLatencyMs: 650, confidenceAvg: 0.99 },
  },
  {
    id: 'legal_governance.policy',
    number: 90,
    name: 'Policy Agent',
    title: 'Policy Lifecycle & Guardrail Enforcement Agent',
    category: 'legal_governance',
    supervisorId: 'sup.governance',
    level: 3,
    description: 'Authors, updates, and evaluates organizational policies, codes of conduct, and acceptable use guidelines.',
    capabilities: ['policy_impact_assessment', 'policy_disambiguation', 'governance_rulebook_authoring'],
    tools: ['policy_management_engine', 'rule_conflict_tester'],
    permissions: ['create_company_policies'],
    memoryScope: ['legal', 'company_wide'],
    riskLevel: 'medium',
    autonomyLevel: 'level_3_approval_required',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '📜',
    metrics: { tasksCompleted: 270, accuracyScore: 98, avgLatencyMs: 580, confidenceAvg: 0.97 },
  },
  {
    id: 'legal_governance.security',
    number: 91,
    name: 'Security Agent',
    title: 'Cybersecurity Threat & Vulnerability Agent',
    category: 'legal_governance',
    supervisorId: 'sup.security',
    level: 3,
    description: 'Monitors threat vectors, zero-day CVE disclosures, IAM over-privileges, and cloud posture misconfigurations.',
    capabilities: ['threat_modeling_stride', 'cve_severity_scoring', 'cloud_security_posture_audit'],
    tools: ['siem_alert_stream', 'cve_nist_database', 'iam_policy_evaluator'],
    permissions: ['read_security_logs', 'quarantine_compromised_tokens'],
    memoryScope: ['security', 'engineering'],
    riskLevel: 'critical',
    autonomyLevel: 'level_3_approval_required',
    defaultModel: 'private_secure',
    status: 'idle',
    avatarIcon: '🔒',
    metrics: { tasksCompleted: 580, accuracyScore: 99, avgLatencyMs: 410, confidenceAvg: 0.99 },
  },
  {
    id: 'legal_governance.privacy',
    number: 92,
    name: 'Privacy Agent',
    title: 'Data Privacy (GDPR/CCPA) & Data Protection Agent',
    category: 'legal_governance',
    supervisorId: 'sup.security',
    level: 3,
    description: 'Manages Data Subject Access Requests (DSAR), RoPA records of processing, and cross-border data transfer rules.',
    capabilities: ['pii_data_flow_mapping', 'dsar_workflow_automation', 'privacy_impact_assessment'],
    tools: ['data_catalog_pii_scanner', 'dsar_orchestrator'],
    permissions: ['inspect_data_schemas', 'enforce_pii_masking'],
    memoryScope: ['security', 'legal'],
    riskLevel: 'high',
    autonomyLevel: 'level_3_approval_required',
    defaultModel: 'private_secure',
    status: 'idle',
    avatarIcon: '🔏',
    metrics: { tasksCompleted: 310, accuracyScore: 100, avgLatencyMs: 470, confidenceAvg: 0.99 },
  },
  {
    id: 'legal_governance.governance',
    number: 93,
    name: 'Governance Agent',
    title: 'AI Alignment & Organization Governance Agent',
    category: 'legal_governance',
    supervisorId: 'sup.governance',
    level: 3,
    description: 'Controls multi-agent execution boundaries, enforces autonomy limits, and halts unauthorized agent behavior.',
    capabilities: ['autonomy_boundary_enforcement', 'hallucination_guardrailing', 'agent_misalignment_detection'],
    tools: ['governance_policy_gate', 'agent_circuit_breaker_switch'],
    permissions: ['halt_agent_execution', 'enforce_human_approval_gate'],
    memoryScope: ['legal', 'company_wide'],
    riskLevel: 'critical',
    autonomyLevel: 'level_4_high_autonomy',
    defaultModel: 'private_secure',
    status: 'idle',
    avatarIcon: '🏛️',
    metrics: { tasksCompleted: 620, accuracyScore: 99, avgLatencyMs: 280, confidenceAvg: 0.99 },
  },
  {
    id: 'legal_governance.audit',
    number: 94,
    name: 'Audit Agent',
    title: 'Immutable Auditability & Traceability Agent',
    category: 'legal_governance',
    supervisorId: 'sup.governance',
    level: 3,
    description: 'Maintains tamper-evident audit trails of every agent decision, tool execution, model call, and human approval.',
    capabilities: ['audit_hash_chaining', 'forensic_reconstruction', 'compliance_reporting'],
    tools: ['immutable_audit_ledger', 'hash_verification_tool'],
    permissions: ['append_audit_records', 'read_all_audit_logs'],
    memoryScope: ['legal', 'company_wide'],
    riskLevel: 'low',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'fast_classifier',
    status: 'idle',
    avatarIcon: '📑',
    metrics: { tasksCompleted: 1450, accuracyScore: 100, avgLatencyMs: 90, confidenceAvg: 1.0 },
  },
  {
    id: 'legal_governance.access_control',
    number: 95,
    name: 'Access Control Agent',
    title: 'RBAC & Agent Permissions Gatekeeper Agent',
    category: 'legal_governance',
    supervisorId: 'sup.security',
    level: 3,
    description: 'Validates cryptographic tokens, scopes tool invocation permissions, and blocks privilege escalation.',
    capabilities: ['least_privilege_enforcement', 'rbac_policy_evaluation', 'token_attestation'],
    tools: ['iam_authz_engine', 'token_validator_service'],
    permissions: ['grant_revoke_agent_scopes'],
    memoryScope: ['security'],
    riskLevel: 'critical',
    autonomyLevel: 'level_4_high_autonomy',
    defaultModel: 'fast_classifier',
    status: 'idle',
    avatarIcon: '🔑',
    metrics: { tasksCompleted: 1800, accuracyScore: 100, avgLatencyMs: 40, confidenceAvg: 1.0 },
  },

  // ==========================================
  // CATEGORY 11: CUSTOMER (96-100)
  // ==========================================
  {
    id: 'customer.support',
    number: 96,
    name: 'Customer Support Agent',
    title: 'Support Intelligence & Ticket Triage Agent',
    category: 'customer',
    supervisorId: 'sup.customer',
    level: 3,
    description: 'Triages customer tickets, identifies recurring incident trends, and suggests high-accuracy automated resolutions.',
    capabilities: ['ticket_intent_classification', 'sentiment_escalation_detection', 'knowledge_base_retrieval'],
    tools: ['zendesk_intercom_api', 'support_kb_search'],
    permissions: ['read_write_support_tickets'],
    memoryScope: ['customer'],
    riskLevel: 'low',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'fast_classifier',
    status: 'idle',
    avatarIcon: '🎧',
    metrics: { tasksCompleted: 1250, accuracyScore: 98, avgLatencyMs: 160, confidenceAvg: 0.97 },
  },
  {
    id: 'customer.success',
    number: 97,
    name: 'Customer Success Agent',
    title: 'Customer Health & Product Adoption Agent',
    category: 'customer',
    supervisorId: 'sup.customer',
    level: 3,
    description: 'Tracks customer health scores, quarterly business reviews (QBRs), feature adoption depth, and renewal risk.',
    capabilities: ['customer_health_scoring', 'qbr_deck_compilation', 'adoption_gap_identification'],
    tools: ['gainsight_customer_db', 'product_usage_telemetry'],
    permissions: ['read_customer_telemetry', 'draft_qbr_reports'],
    memoryScope: ['customer', 'sales'],
    riskLevel: 'medium',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '🤝',
    metrics: { tasksCompleted: 430, accuracyScore: 97, avgLatencyMs: 610, confidenceAvg: 0.95 },
  },
  {
    id: 'customer.feedback',
    number: 98,
    name: 'Feedback Agent',
    title: 'NPS & Voice of Customer (VoC) Agent',
    category: 'customer',
    supervisorId: 'sup.customer',
    level: 3,
    description: 'Aggregates reviews (G2, Trustpilot), in-app NPS surveys, and customer complaint themes.',
    capabilities: ['voc_theme_clustering', 'nps_driver_analysis', 'competitor_review_benchmarking'],
    tools: ['review_aggregator_feed', 'nps_survey_database'],
    permissions: ['read_customer_feedback'],
    memoryScope: ['customer', 'product'],
    riskLevel: 'low',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '⭐',
    metrics: { tasksCompleted: 510, accuracyScore: 96, avgLatencyMs: 450, confidenceAvg: 0.95 },
  },
  {
    id: 'customer.retention',
    number: 99,
    name: 'Retention Agent',
    title: 'Churn Prevention & Account Retention Agent',
    category: 'customer',
    supervisorId: 'sup.customer',
    level: 3,
    description: 'Predicts imminent account cancellations, identifies early disengagement patterns, and designs retention offers.',
    capabilities: ['churn_hazard_modeling', 'at_risk_intervention_playbooks', 'renewal_probability_prediction'],
    tools: ['churn_predictive_model', 'retention_playbook_db'],
    permissions: ['read_account_health', 'propose_retention_offers'],
    memoryScope: ['customer', 'sales', 'finance'],
    riskLevel: 'medium',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '🔄',
    metrics: { tasksCompleted: 380, accuracyScore: 97, avgLatencyMs: 580, confidenceAvg: 0.96 },
  },
  {
    id: 'customer.intelligence',
    number: 100,
    name: 'Customer Intelligence Agent',
    title: 'Customer Lifetime Value (LTV) & Segmentation Agent',
    category: 'customer',
    supervisorId: 'sup.customer',
    level: 3,
    description: 'Builds longitudinal customer cohort analyses, predictive LTV models, and behavioral persona clusters.',
    capabilities: ['predictive_ltv_estimation', 'cohort_retention_curves', 'behavioral_segmentation_kmeans'],
    tools: ['customer_data_platform_cdp', 'cohort_matrix_calculator'],
    permissions: ['read_customer_intelligence'],
    memoryScope: ['customer', 'marketing', 'strategy'],
    riskLevel: 'low',
    autonomyLevel: 'level_2_low_risk_auto',
    defaultModel: 'reasoning_strategy',
    status: 'idle',
    avatarIcon: '💎',
    metrics: { tasksCompleted: 460, accuracyScore: 98, avgLatencyMs: 670, confidenceAvg: 0.97 },
  },
];

// Quick index lookup maps
export const AGENT_BY_ID = new Map<string, AgentDefinition>(
  ALL_100_AGENTS.map((agent) => [agent.id, agent])
);
export const AGENT_BY_NUMBER = new Map<number, AgentDefinition>(
  ALL_100_AGENTS.map((agent) => [agent.number, agent])
);
